"""Configuration defaults for chunk generation."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT_DIR = PROJECT_ROOT / "data" / "processed"
DEFAULT_CHUNKS_DIR = PROJECT_ROOT / "data" / "processed" / "chunks"
DEFAULT_PARENT_CHUNKS_PATH = DEFAULT_CHUNKS_DIR / "parents.jsonl"
DEFAULT_MANIFEST_PATH = PROJECT_ROOT / "data" / "processed" / "source_manifest.json"
GENERATED_CHUNKING_DIRS = {DEFAULT_CHUNKS_DIR}

DEFAULT_WINDOW_TOKENS = 280
DEFAULT_OVERLAP_TOKENS = 45
DEFAULT_MIN_TOKENS = 40
DEFAULT_MAX_TOKENS = 420

SLIDING_WINDOW_STRATEGY = "sliding_window"
SEMANTIC_CHUNKING_STRATEGY = "semantic_chunking"
REGEX_CONSTRAINED_SEMANTIC_STRATEGY = "regex_constrained_semantic"

STRATEGY_OUTPUTS = {
    SLIDING_WINDOW_STRATEGY: DEFAULT_CHUNKS_DIR / SLIDING_WINDOW_STRATEGY / "chunks.jsonl",
    SEMANTIC_CHUNKING_STRATEGY: DEFAULT_CHUNKS_DIR / SEMANTIC_CHUNKING_STRATEGY / "chunks.jsonl",
    REGEX_CONSTRAINED_SEMANTIC_STRATEGY: DEFAULT_CHUNKS_DIR / REGEX_CONSTRAINED_SEMANTIC_STRATEGY / "chunks.jsonl",
}
