"""Tests for LangChain RAG LLM helpers."""

import types
import unittest
from unittest.mock import patch

import agents.consulta_normativa.langchain_rag as langchain_rag
from agents.consulta_normativa.langchain_rag.core import llm as llm_module
from agents.consulta_normativa.langchain_rag.core.llm import extract_response_content, invoke_llm_text


class LangChainRagLlmTest(unittest.TestCase):
    """Verify LLM helper behavior with fakes only."""

    def test_extract_response_content_reads_message_content(self) -> None:
        response = types.SimpleNamespace(content="Generated answer.")

        self.assertEqual(extract_response_content(response), "Generated answer.")

    def test_extract_response_content_reads_last_message_with_content(self) -> None:
        response = [types.SimpleNamespace(content="first"), types.SimpleNamespace(content="last")]

        self.assertEqual(extract_response_content(response), "last")

    def test_extract_response_content_falls_back_to_string(self) -> None:
        self.assertEqual(extract_response_content(123), "123")

    def test_invoke_llm_text_invokes_llm_and_extracts_content(self) -> None:
        llm = FakeLlm()
        messages = [object()]

        answer = invoke_llm_text(llm, messages)

        self.assertEqual(answer, "Generated by fake LLM.")
        self.assertEqual(llm.messages, [messages])

    def test_package_exports_build_groq_llm_from_core_path(self) -> None:
        self.assertIs(langchain_rag.build_groq_llm, llm_module.build_groq_llm)

    def test_build_groq_llm_checks_api_key_before_optional_import(self) -> None:
        with patch.dict("os.environ", {}, clear=True):
            with self.assertRaises(ValueError) as context:
                llm_module.build_groq_llm()

        self.assertIn("GROQ_API_KEY", str(context.exception))


class FakeLlm:
    """Small LangChain-like fake that records invocation input."""

    def __init__(self) -> None:
        self.messages: list[list[object]] = []

    def invoke(self, messages: list[object]) -> object:
        self.messages.append(messages)
        return types.SimpleNamespace(content="Generated by fake LLM.")


if __name__ == "__main__":
    unittest.main()
